spring:
  application:
    name: jongmin

  jpa:
    # ?? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # ??? ?? ? data.sql ??
    defer-datasource-initialization: true

    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
